---
three_d:
- .3mf
- .stl
docs:
- .doc
- .docx
- .json
- .log
- .odt
- .pdf
- .txt
ebooks:
- .epub
- .mobi
excel:
- .csv
- .parquet
- .xls
- .xlsm
- .xlsx
images:
- .jpg
- .jpeg
- .jpe
- .jif
- .jfif
- .jfi
- .png
- .gif
- .webp
- .tiff
- .tif
- .psd
- .raw
- .arw
- .cr2
- .nrw
- .k25
- .bmp
- .dib
- .heif
- .heic
- .ind
- .indd
- .indt
- .jp2
- .j2k
- .jpf
- .jpx
- .jpm
- .mj2
- .svg
- .svgz
- .ai
- .eps
- .ico
powerbi:
- .pbids
- .pbit
- .pbix
- .potx
- .rdl
- .rdlc
- .rsix
- .pbitx
- .pbix.d
- .pbitm
- .pbix.tmp
- .pbit.tmp
- .pbix.asdatabase
- .pbix.aspkg
- .pbix.aspac
- .pbix.asrepo
- .pbix.asperational
- .pbix.layout
- .pbiviz
- .rsds
powerpoint:
- .ppt
- .pptx
programs:
- .AppImage
- .apk
- .exe
- .msi
python:
- .ipynb
- .py
sql:
- .sql
videos:
- .webm
- .mpg
- .mp2
- .mpeg
- .mpe
- .mpv
- .ogg
- .mp4
- .mp4v
- .m4v
- .avi
- .wmv
- .mov
- .qt
- .flv
- .swf
- .avchd
web:
- .htm
- .html
zips:
- .7z
- .deb
- .gz
- .rar
- .tar
- .tar.xy
- .tar.xz
- .tgz
- .zip
